"""Generate a Blender Python script that builds a tree (or forest) and renders.

Blender's native file format (``.blend``) is a binary memory-dump of its
internal C structures, and the canonical way to construct or read one is
through Blender's own ``bpy`` API. This module side-steps the
binary-format problem by emitting a self-contained Python script that you
run inside Blender::

    /Applications/Blender.app/Contents/MacOS/Blender --background \\
        --python /path/to/render_my_tree.py

The generated script imports ``bpy``, builds one cylinder per branch from
the tree's typed mechanics fields, applies materials by Strahler order,
adds a sun + ground plane, and saves a render to PNG (and optionally a
``.blend``). The trees in `~/Documents/Arbres/Blender/` used for the
*Nat. Commun.* figures were authored directly in Blender; this exporter
is the programmatic equivalent so you can re-render any simulated tree.
"""

from __future__ import annotations

import json
from pathlib import Path

from mechatree._core import PyTree

# Template for the Blender script. Kept at module scope (column 0) so the
# indentation in the generated file is what Blender expects — the previous
# in-function ``textwrap.dedent`` version was defeated by the embedded JSON
# payload, which sits at column 0 inside the outer string and caused dedent
# to find a 0-column common prefix.
_BLENDER_TEMPLATE = '''"""Auto-generated by mechatree.export.to_blender_script.

Run with:
    blender --background --python {script_name}
"""

import bpy
import json
import math
from mathutils import Vector

PAYLOAD = json.loads(r"""{payload_json}""")


def _clear_scene() -> None:
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for block in (bpy.data.meshes, bpy.data.materials,
                  bpy.data.lights, bpy.data.cameras):
        for item in list(block):
            block.remove(item)


def _make_material(name, rgb):
    mat = bpy.data.materials.new(name=name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf is not None:
        bsdf.inputs["Base Color"].default_value = (rgb[0], rgb[1], rgb[2], 1.0)
        if "Roughness" in bsdf.inputs:
            bsdf.inputs["Roughness"].default_value = 0.6
    return mat


def _add_branch(loc, unit_t, length, diameter, material):
    """Create one cylinder from `loc` along `unit_t` with the given length."""
    mid = Vector(loc) + 0.5 * length * Vector(unit_t)
    # Default cylinder axis is +Z; rotate so it lies along unit_t.
    axis_z = Vector((0.0, 0.0, 1.0))
    tip_dir = Vector(unit_t)
    if tip_dir.length < 1e-9:
        rot = (0.0, 0.0, 0.0)
    else:
        tip_dir.normalize()
        quat = axis_z.rotation_difference(tip_dir)
        rot = quat.to_euler()
    bpy.ops.mesh.primitive_cylinder_add(
        radius=max(diameter / 2.0, 1e-4),
        depth=max(length, 1e-4),
        location=mid,
        rotation=rot,
    )
    obj = bpy.context.active_object
    obj.data.materials.append(material)
    for poly in obj.data.polygons:
        poly.use_smooth = True
    return obj


def _add_leaf_marker(tip, leaf_material, radius):
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=radius, location=tip, segments=12, ring_count=8
    )
    obj = bpy.context.active_object
    obj.data.materials.append(leaf_material)
    for poly in obj.data.polygons:
        poly.use_smooth = True


def _setup_camera_and_light(centre, extent):
    cam_offset = Vector(PAYLOAD["camera_offset"])
    cam_data = bpy.data.cameras.new(name="Camera")
    cam_data.lens = 50.0
    cam_obj = bpy.data.objects.new("Camera", cam_data)
    cam_obj.location = Vector(centre) + cam_offset * max(1.0, extent / 20.0)
    bpy.context.scene.collection.objects.link(cam_obj)
    direction = Vector(centre) - cam_obj.location
    cam_obj.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()
    bpy.context.scene.camera = cam_obj

    sun_data = bpy.data.lights.new(name="Sun", type="SUN")
    sun_data.energy = 5.0
    sun_obj = bpy.data.objects.new(name="Sun", object_data=sun_data)
    sun_obj.location = (10.0, -10.0, 20.0)
    sun_obj.rotation_euler = (math.radians(40), 0.0, math.radians(30))
    bpy.context.scene.collection.objects.link(sun_obj)


def main():
    _clear_scene()

    palette = PAYLOAD["palette"]
    materials = [
        _make_material("Branch_order_{{0}}".format(k + 1), rgb)
        for k, rgb in enumerate(palette)
    ]
    leaf_mat = _make_material("Leaf", PAYLOAD["leaf_color"])

    branches = PAYLOAD["branches"]
    if not branches:
        print("No branches to render.")
        return

    xs, ys, zs = [], [], []
    for b in branches:
        xs.append(b["location"][0])
        ys.append(b["location"][1])
        zs.append(b["location"][2] + b["length"])
        mat = materials[(b["strahler"] - 1) % len(materials)]
        _add_branch(b["location"], b["unit_t"], b["length"],
                    b["diameter"], mat)
        if b["is_leaf"]:
            tip = [
                b["location"][0] + b["length"] * b["unit_t"][0],
                b["location"][1] + b["length"] * b["unit_t"][1],
                b["location"][2] + b["length"] * b["unit_t"][2],
            ]
            _add_leaf_marker(tip, leaf_mat, max(b["diameter"], 0.05))

    cx = sum(xs) / len(xs)
    cy = sum(ys) / len(ys)
    cz = sum(zs) / len(zs) * 0.5
    extent = max(
        max(xs) - min(xs),
        max(ys) - min(ys),
        max(zs) - min(zs),
        1.0,
    )

    if PAYLOAD["add_ground"]:
        bpy.ops.mesh.primitive_plane_add(
            size=4.0 * extent, location=(cx, cy, 0.0)
        )
        ground_mat = _make_material("Ground", (0.45, 0.5, 0.4))
        bpy.context.active_object.data.materials.append(ground_mat)

    _setup_camera_and_light((cx, cy, cz), extent)

    scene = bpy.context.scene
    scene.render.resolution_x = PAYLOAD["image_resolution"][0]
    scene.render.resolution_y = PAYLOAD["image_resolution"][1]
    # Blender 4.2+ ships EEVEE-Next; earlier versions ship EEVEE. Either
    # works for the simple materials we use.
    for engine in ("BLENDER_EEVEE_NEXT", "BLENDER_EEVEE"):
        try:
            scene.render.engine = engine
            break
        except TypeError:
            continue
    scene.world = scene.world or bpy.data.worlds.new("World")
    scene.world.use_nodes = True
    bg = scene.world.node_tree.nodes.get("Background")
    if bg is not None:
        bg.inputs["Color"].default_value = (0.92, 0.94, 0.98, 1.0)
        bg.inputs["Strength"].default_value = 1.0

    if PAYLOAD["render_path"]:
        scene.render.filepath = PAYLOAD["render_path"]
        bpy.ops.render.render(write_still=True)
        print("Rendered: " + PAYLOAD["render_path"])

    if PAYLOAD["save_blend_path"]:
        bpy.ops.wm.save_as_mainfile(filepath=PAYLOAD["save_blend_path"])
        print("Saved scene: " + PAYLOAD["save_blend_path"])


if __name__ == "__main__":
    main()
'''

# Default colour palette (RGB 0..1) — matches the 6-colour discrete map
# from ``plot_single_tree_3D_flat.m``.
_DEFAULT_PALETTE: list[tuple[float, float, float]] = [
    (14 / 255, 74 / 255, 106 / 255),
    (103 / 255, 167 / 255, 208 / 255),
    (185 / 255, 226 / 255, 251 / 255),
    (248 / 255, 208 / 255, 190 / 255),
    (224 / 255, 128 / 255, 105 / 255),
    (173 / 255, 12 / 255, 1 / 255),
]


def _collect_branches(tree: PyTree, set_strahler: bool = True) -> list[dict]:
    """Snapshot every branch as a plain JSON-serialisable dict."""
    if set_strahler:
        tree.set_strahler()
    n = tree.get_number_of_branches()
    out: list[dict] = []
    for i in range(n):
        out.append(
            {
                "location": list(tree.get_location(i)),
                "unit_t": list(tree.get_unit_t(i)),
                "length": tree.get_length(i),
                "diameter": tree.get_diameter(i),
                "strahler": tree.get_strahler(i) if set_strahler else 0,
                "is_leaf": tree.get_number_of_children(i) == 0,
            }
        )
    return out


def to_blender_script(
    tree_or_forest,
    output_path: str | Path,
    *,
    render_path: str | Path | None = None,
    save_blend_path: str | Path | None = None,
    palette: list[tuple[float, float, float]] | None = None,
    image_resolution: tuple[int, int] = (1920, 1080),
    camera_offset: tuple[float, float, float] = (-25.0, -25.0, 20.0),
    add_ground: bool = True,
    leaf_color: tuple[float, float, float] = (0.2, 0.6, 0.15),
) -> Path:
    """Write a standalone Blender Python script.

    Parameters
    ----------
    tree_or_forest:
        A :class:`mechatree._core.PyTree` *or* a
        :class:`mechatree.forest.Forest` to render.
    output_path:
        File path the script is written to.
    render_path:
        If given, the script saves a rendered PNG to this path. Omit to
        skip rendering (useful when you'll open the file interactively).
    save_blend_path:
        If given, the script saves a ``.blend`` file to this path. Open
        it later in Blender to inspect / edit the scene.
    palette:
        Per-Strahler-order RGB tuples. Defaults to the 6-colour map used
        in the *Nat. Commun.* paper figures. Strahler orders beyond the
        palette length wrap around.
    image_resolution:
        Output PNG resolution.
    camera_offset:
        Camera position relative to the tree's centre (defaults to
        looking down at ~45° from the south-west, like the MATLAB scripts).
    add_ground:
        Add a light-grey ground plane at z=0.
    leaf_color:
        RGB colour for the leaf accent spheres at each tip.

    Returns
    -------
    Path
        Resolved path to the written script.
    """
    output_path = Path(output_path).resolve()

    # Lazy import — only needed when called with a Forest argument.
    branches: list[dict] = []
    tree_count = 1
    try:
        from mechatree.forest import Forest

        is_forest = isinstance(tree_or_forest, Forest)
    except ImportError:
        is_forest = False

    if is_forest:
        forest = tree_or_forest
        for tree in forest.trees:
            branches.extend(_collect_branches(tree))
        tree_count = len(forest.trees)
    else:
        branches = _collect_branches(tree_or_forest)

    if palette is None:
        palette = _DEFAULT_PALETTE

    payload = {
        "branches": branches,
        "palette": [list(c) for c in palette],
        "leaf_color": list(leaf_color),
        "render_path": str(Path(render_path).resolve()) if render_path else None,
        "save_blend_path": str(Path(save_blend_path).resolve()) if save_blend_path else None,
        "image_resolution": list(image_resolution),
        "camera_offset": list(camera_offset),
        "add_ground": add_ground,
        "tree_count": tree_count,
    }
    payload_json = json.dumps(payload, indent=2)

    script = _BLENDER_TEMPLATE.format(
        script_name=output_path.name,
        payload_json=payload_json,
    )
    output_path.write_text(script)
    return output_path


__all__ = ["to_blender_script"]
