#cython: language_level=3
#cython: wraparound=False
#cython: boundscheck=False
#cython: cdivision=True

import sys
import cython
import math

"""
Function declaration: distance_test(PyTree tree,int i,double influenceRadius)
 - This function tests if the tip of branch at index "i" is too close of some
 other branch (except for its parent and brother) of "tree". It returns 1 if it is
 and 0 if it's not.
"""

def distance_test(tree, int i, double influenceRadius):

    """
    Variable declaration
    """
    cdef double x_0
    cdef double y_0
    cdef double L
    cdef double theta
    cdef double x_tip
    cdef double y_tip
    cdef int N
    cdef int parent_index
    cdef int brother_index
    cdef int j
    cdef double xi
    cdef double yi
    cdef double th
    cdef double d
    cdef double xf
    cdef double yf
    cdef double hi
    cdef double hf
    cdef double di
    cdef double df

    """
    Retrieving branch's properties with the "get_property" function
    """
    x_0=tree.get_property(i,"x")
    y_0=tree.get_property(i,"y")
    L=tree.get_property(i,"L")
    theta=tree.get_property(i,"theta")

    """
    Calculating coordinates of the tip
    """
    x_tip=x_0+L*math.sin(theta)
    y_tip=y_0+L*math.cos(theta)

    """
    Retrieving coral's number of branches
    """
    N=tree.get_number_of_branches()

    """
    Retrieving parent and brother index, if the branch isn't the trunk
    """
    if tree.has_parent(i)==1:
        parent_index=tree.get_parent_index(i)
        brother_index=tree.get_brothers_index(i)

    """
    Traversing the coral
    """
    j=0
    for j in range(N):

        """
        We don't test the distance:
         - of a branch with itself (i!=j)
         - of a branch with its father (j!=parent_index)
         - of a branch with its brother (j!=brother_index)
        """
        if i!=j and j!=parent_index and j!=brother_index:

            """
            Retrieving branch's j properties
            """
            xi=tree.get_property(j,"x")
            yi=tree.get_property(j,"y")
            th=tree.get_property(j,"theta")
            L=tree.get_property(j,"L")

            """
            Calculating the distance between branch's i tip and the line
            generated by branch j
            """
            d=math.fabs((x_tip-xi)/math.tan(th)-(y_tip-yi))/math.sqrt((1/math.tan(th))**2+1)

            """
            Calculating branch's j tip coordinates
            """
            xf=xi+L*math.sin(th)
            yf=yi+L*math.cos(th)

            """
            Calculating the distance between branch's i tip and branch's j
            origin (hi) and tip (hf)
            """
            hi=math.sqrt((x_tip-xi)**2+(y_tip-yi)**2)
            hf=math.sqrt((x_tip-xf)**2+(y_tip-yf)**2)

            """
            Calculating the distance between the orthogonal projection of
            branch's i tip on the line generated by branch j and branch's j
            origin (di) and tip (df)
            """
            di=math.sqrt(hi**2-d**2)
            df=math.sqrt(hf**2-d**2)

            """
            If the orthogonal projection belongs to the branch...
            """
            if di<tree.get_property(j,"L") and df<tree.get_property(j,"L"):

                """
                ... and if the distance between the orthogonal projection of
                branch i on branch j and branch's i tip is smaller than two
                times the thickness of the influence zone, branch i can't
                continue to grow
                """
                if d<=1*influenceRadius:
                    """
                    The value of grow property is changed with the
                    set_property function
                    """
                    return 0

            else:
                """
                If the distance between branch's i tip and one of branch's j
                extremities is inferior to two times the thickness of the
                influence zone, branch i can't continue to grow
                """
                if hi<=1*influenceRadius or hf<=1*influenceRadius:
                    return 0
    return 1
