#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import math
import random
import numpy as np

from pytree import PyTree
from matplotlib import pyplot as plt

"""
Parameters
"""

T=380 # total simulation time

dL=0.1 # length added to growing branches at each time step
mean_angle=math.pi/3 # mean branching angle
std_angle=math.pi/10 # standard deviation for the branching angle
influenceRadius=5*dL # thickness of the influence zone


p_b=0.2 # branching probability
L_b=2*influenceRadius

###############################################################################

def plot_tree(tree,fignum):
    plt.axis('off') # no axis
    for i in range(tree.get_number_of_branches()):
        x1=tree.get_property(i,"x")
        z1=tree.get_property(i,"y")

        x2=x1+(tree.get_property(i,"L")*math.sin(tree.get_property(i,"theta")))
        z2=z1+(tree.get_property(i,"L")*math.cos(tree.get_property(i,"theta")))

        plt.figure(1) # creation of the figure
        plt.plot([x1,x2],[z1,z2],'red',linewidth=1)

    script_dir = os.path.dirname(__file__)
    results_dir = os.path.join(script_dir, 'selfAvoid/')

    if fignum<10:
        num=str(0)*3+str(fignum)
    elif fignum>=10 and fignum<100:
        num=str(0)*2+str(fignum)
    elif fignum>=100 and fignum<1000:
        num=str(0)*1+str(fignum)
    else:
        num=str(fignum)

    title="fig"
    form=".png"
    figname=title+num+form
    plt.savefig(results_dir+figname)
    plt.close()

###############################################################################

"""
Coral initialisation:
  - x,y: coordinates of trunk's origin
  - theta: direction of the trunk. Angle between the trunk and vertical axis
  - L: initial length of the trunk
  - grow: if grow==1 the trunk can grow, if grow==0 it can't

  These are the properties of the trunk. Each time that a new branch is created,
  it will be initialised with the same properties but with different values.
"""

trunk={"x":0,"y":0,"theta":10**-6,"L":2,"grow":1}
coral=PyTree(trunk)


"""
Function declaration: distance_test(coral,i)
 - this function tests if the tip of branch at index "i" is too close of some
 other branch (except for its parent and brother) of "coral"
"""

def distance_test(coral,i):

    """
    Retrieving branch's properties with the "get_property" function
    """
    x_0=coral.get_property(i,"x")
    y_0=coral.get_property(i,"y")
    L=coral.get_property(i,"L")
    theta=coral.get_property(i,"theta")

    """
    Calculating coordinates of the tip
    """
    x_tip=x_0+L*math.sin(theta)
    y_tip=y_0+L*math.cos(theta)

    """
    Retrieving coral's number of branches
    """
    N=coral.get_number_of_branches()

    """
    Retrieving parent and brother index, if the branch isn't the trunk
    """
    if coral.has_parent(i)==1:
        parent_index=coral.get_parent_index(i)
        brother_index=coral.get_brothers_index(i)

    """
    Traversing the coral
    """
    for j in range(N):

        """
        We don't test the distance:
         - of a branch with itself (i!=j)
         - of a branch with its father (j!=parent_index)
         - of a branch with its brother (j!=brother_index)
        """
        if i!=j and j!=parent_index and j!=brother_index:

            """
            Retrieving branch's j properties
            """
            xi=coral.get_property(j,"x")
            yi=coral.get_property(j,"y")
            th=coral.get_property(j,"theta")
            L=coral.get_property(j,"L")

            """
            Calculating the distance between branch's i tip and the line
            generated by branch j
            """
            d=math.fabs((x_tip-xi)/math.tan(th)-(y_tip-yi))/math.sqrt((1/math.tan(th))**2+1)

            """
            Calculating branch's j tip coordinates
            """
            xf=xi+L*math.sin(th)
            yf=yi+L*math.cos(th)

            """
            Calculating the distance between branch's i tip and branch's j
            origin (hi) and tip (hf)
            """
            hi=math.sqrt((x_tip-xi)**2+(y_tip-yi)**2)
            hf=math.sqrt((x_tip-xf)**2+(y_tip-yf)**2)

            """
            Calculating the distance between the orthogonal projection of
            branch's i tip on the line generated by branch j and branch's j
            origin (di) and tip (df)
            """
            di=math.sqrt(hi**2-d**2)
            df=math.sqrt(hf**2-d**2)

            """
            If the orthogonal projection belongs to the branch...
            """
            if di<coral.get_property(j,"L") and df<coral.get_property(j,"L"):

                """
                ... and if the distance between the orthogonal projection of
                branch i on branch j and branch's i tip is smaller than two
                times the thickness of the influence zone, branch i can't
                continue to grow
                """
                if d<=1*influenceRadius:
                    """
                    The value of grow property is changed with the
                    set_property function
                    """
                    coral.set_property(i,"grow",0)
                    return None

            else:
                """
                If the distance between branch's i tip and one of branch's j
                extremities is inferior to two times the thickness of the
                influence zone, branch i can't continue to grow
                """
                if hi<=1*influenceRadius or hf<=1*influenceRadius:
                    coral.set_property(i,"grow",0)
                    return None


"""
Growth simulation
"""

for i in range(T):

    plot_tree(coral,i)

    """
    Traversing the tree to simulate growth of every branch: growing loop
    """
    nb=coral.get_number_of_branches()
    for n in range(nb):

        """
        If the branch can't grow we pass to the next branch
        """
        if coral.get_property(n,"grow")==1:

            """
            Avoiding branches to traverse the ground
            """
            y_0=coral.get_property(n,"y")
            L=coral.get_property(n,"L")
            theta=coral.get_property(n,"theta")

            y_tip=y_0+L*math.cos(theta)

            if y_tip<0.5:
                coral.set_property(n,"grow",0)

            """
            Realizing distance test for branch n
            """
            distance_test(coral,n)
            """
            If it can grow, dL is added to its actual length, if not we pass to
            the next branch
            """
            if coral.get_property(n,"grow")==1:
                L=coral.get_property(n,"L")
                coral.set_property(n,"L",L+dL)

    #--------------------------------------------------------------------------
    """
    Traversing the tree to simulate branching for every branch: branching loop
    """
    nb=coral.get_number_of_branches()
    n=0
    while n<nb:
        """
        If branch isn't allowed to grow, then it isn't allowed to ramify, then
        we pass to the next branch
        """
        if coral.get_property(n,"grow")==1:

            """
            If random number is smaller than branching probability and if branch
            n is long enough to ramify
            """
            if random.random()<=p_b and coral.get_property(n,"L")>L_b:

                """
                Angle between the two new branches is chosen randomly
                """
                angle=random.gauss(mean_angle,std_angle)
                """
                Ramification is symmetrical
                """
                thetaplus=coral.get_property(n,"theta")+angle/2
                thetaminu=coral.get_property(n,"theta")-angle/2

                """
                The origin of the new branches has the same coordinates
                (x_0,y_0) than the parent's tip
                """
                x=coral.get_property(n,"x")
                y=coral.get_property(n,"y")
                L=coral.get_property(n,"L")
                theta=coral.get_property(n,"theta")

                x_0=x+L*math.sin(theta)
                y_0=y+L*math.cos(theta)

                """
                New branches initialisation
                """
                branch_init1={"x":x_0,"y":y_0,"theta":thetaplus,"L":0,"grow":1}
                branch_init2={"x":x_0,"y":y_0,"theta":thetaminu,"L":0,"grow":1}
                """
                New branches are added to branch n with the "add_branch"
                function
                """
                coral.add_branch(n,branch_init1)
                coral.add_branch(n,branch_init2)

                """
                The new parent can't grow anymore
                """
                coral.set_property(n,"grow",0)
                """
                Skipping the newly created branches in the loop
                """
                n=n+2
                """
                Actualizing the number of branches in the coral
                """
                nb=coral.get_number_of_branches()

        """
        Passing to the next branch
        """
        n=n+1
